experiment:
  ensemble:    
    number_of_networks: 30   
    network:
      implementation: NetworkTF #tensorflow 
      hyperparameters:
        layerwidths: [1, 100, 1]
        activation_function: tanh
        output_activation_function: linear
        scale_weighted_sum: one_over_root_n
        training:          
          learning_rate: 0.01          
          loss_function: mean_squared_error
      initial_parameters:
        source: generate                         
        generate:
          random_seed: 10269
          weights:
            distribution: gaussian
            mean: 0
            variance: 1
          biases:
            distribution: gaussian
            mean: 0
            variance: 1
  data:  
    source: generate
    generate:
      input:      
        min: 0
        max: 1      
        size: 100
        spacing: linear
        training_data_ratio: 0.3
      output:
        function: legendre
        parameters:
          #change degree for each run
          coefficients: [0,0,0,0,1,0,0,0,0,0,0]
        noise:        
          distribution: gaussian
          random_seed: 10313
          mean: 0
          variance: 0
  steps: 
    source: range
    range:
      start: 0
      stop: 10000000
      step: 500 
  graphics:
    training:  
      - graphs: [training_data, ensemble, ensemble_average, theory]
        x_lim: [-0.1,1.1]
        y_lim: [-1.5, 1.5]            
  results:
    loss_threshold: 0.01
    analytic_order: O1
     
   


